apiVersion: v1
kind: Service
metadata:
  name: chioma-backend
  namespace: production
  labels:
    app: chioma-backend
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
    prometheus.io/path: '/metrics'
spec:
  type: ClusterIP
  selector:
    app: chioma-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 3000
      protocol: TCP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
