'use client';
import { Bell } from 'lucide-react';

export default function TenantNotificationsPage() {
  return (
    <div className="p-6">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold text-white">Notifications</h1>
        <button className="text-sm text-blue-400 hover:text-blue-300">Mark all as read</button>
      </div>
      
      <div className="bg-slate-800/50 border border-white/10 rounded-2xl shadow-xl overflow-hidden">
        <div className="p-12 flex flex-col items-center text-center">
          <Bell className="w-12 h-12 text-slate-500 mb-4 opacity-50" />
          <h3 className="text-lg font-medium text-white mb-1">Catch up complete!</h3>
          <p className="text-slate-400">You don&apos;t have any unread notifications generated by the platform.</p>
        </div>
      </div>
    </div>
  );
}
